### ISSUE TITLE
Backstage 1.23.4 breaks Harbor Plugin UI widget

### ISSUE THREAD

**Issue by georgblumenschein** [BESTSELLER/backstage-plugin-harbor#269]
**Problem**

The harbor widget does not render anymore after a update of Backstage to 1.23.4

**Error**

```
TypeError: at.pointer.transition is not a function

    at kt (https://backstage.internal.dynatrace.com/static/9033.18396d5b.chunk.js:32:90288)

    at lt.value (https://backstage.internal.dynatrace.com/static/9033.18396d5b.chunk.js:32:99857)

    at lt.value (https://backstage.internal.dynatrace.com/static/9033.18396d5b.chunk.js:32:99409)

    at $s (https://backstage.internal.dynatrace.com/static/module-react-dom.9141fc70.js:16:31528)

    at Ws (https://backstage.internal.dynatrace.com/static/module-react-dom.9141fc70.js:16:31313)

    at Xc (https://backstage.internal.dynatrace.com/static/module-react-dom.9141fc70.js:16:30864)

    at bc (https://backstage.internal.dynatrace.com/static/module-react-dom.9141fc70.js:16:40596)

    at Sn (https://backstage.internal.dynatrace.com/static/module-react-dom.9141fc70.js:16:39966)

    at Gs (https://backstage.internal.dynatrace.com/static/module-react-dom.9141fc70.js:16:36648)

    at Je (https://backstage.internal.dynatrace.com/static/module-react-dom.9141fc70.js:14:3259)
```

**Proposed Solution**

Fixed locally by updating the d3 components to the next version

```   
 "d3-selection": "^3",
 "d3-transition": "^3",
 "react-d3-speedometer": "^2",
```

**Similar Tickets?**

https://github.com/container-registry/backstage-plugin-harbor/issues/229

**Will the reporter open a PR himself?**

Yes
